### ISSUE TITLE
Update for RDS to support K8S "bound service account token volumes"

### ISSUE THREAD

**Issue by zmailloux** [cloudprober/cloudprober#283]
With kubernetes version [1.21.14](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume), the ability to have rotating service account tokens was added via "Bound service account token volumes".

This presents a problem as cloudprober's RDS feature only loads the service account authentication token [once](https://github.com/cloudprober/cloudprober/blob/faf919afeba3b2e447d8da248ea9f7a5757a5cda/rds/kubernetes/client.go#L102-L138) when the client is created. I am proposing either adding a mechanism to re-load the service account token, or to switch to another library like https://github.com/kubernetes/client-go rather than go-http-client/2.0 which does so already by default.

For more information, the [README](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md) on bound service account tokens has more information. Noteworthy points are:

> Update all workloads to newer version of officially supported Kubernetes client libraries to reload token

and

> For community-maintained client libraries, feel free to contribute to them if the reloading logic is missing

**Comment by manugarg** [comment]
Hey Zach!! Hope you're doing well :)

Thanks for filing this. Good catch. I plan to switch to client-go eventually, it will need some work though. In the meantime, I'll modify the RDS code to get the expiration information from the token and get the new token if needed.

**Comment by manugarg** [comment]
For reference, if I am looking at it correctly, client-go simply renews the token every minute:
https://github.com/kubernetes/client-go/blob/1ea719588ec9fc3b8ed75c76ba8cdb6b75006ca8/transport/token_source.go#L127

https://github.com/kubernetes/client-go/blob/1ea719588ec9fc3b8ed75c76ba8cdb6b75006ca8/transport/token_source.go#L73

This will be the simplest to implement, though we could also just decode the jwt token and get expiry from there. I'll keep looking.

**Comment by manugarg** [comment]
@zmailloux @yashsarma @SamGearou

This is done. "main" tag will have the latest changes. Also I'll cut a new release on Monday (Feb 27), you'll then be able to use the "latest" and "v0.12.4" tags for these changes.

While I've attention of you 😀 :
If you're still using Cloudprober for API probing, I've added a couple of changes to Cloudprober since I left RH, which will allow you to do API probing without writing any code for the external probe:

1. You can validate the API response using [JSON validator](https://github.com/cloudprober/cloudprober/blob/8f819417ca3587b4df25fb469685f43008507b6d/validators/json/proto/config.proto#L8).
2. You can configure HTTP probe to retrieve OAuth tokens from another URL (#275).

An example config to show how these two changes work together to allow API probing without writing any external probe code: https://github.com/cloudprober/cloudprober/pull/275#issuecomment-1427504783

I think these changes will allow you to deploy new API probes at a much faster pace.

Another change that you may find useful is simplification of how do we define k8s targets: #276  ([example config](https://github.com/cloudprober/cloudprober/pull/276#issuecomment-1432258535))

Cheers,
Manu

**Comment by zmailloux** [comment]
Awesome, thanks so much @manugarg ! I will go ahead and give this a go come Monday, and I look forward to trying out some of the other new features you've added. Right now a bulk of our testing is API probing, and the OAuth token change will be very valuable once I get it implemented correctly.

Thanks again, and I hope all is well!

Cheers,
Zach

**Comment by manugarg** [comment]
Zach,

I just cut a new release (v0.12.4 and latest tags should have it). I'll go ahead and close this issue now. Feel free to re-open it if you encounter any issues.
