### ISSUE TITLE
Capture stderr outputs even  when external probe with once mode successfully exits

### ISSUE THREAD

**Issue by koncha99** [cloudprober/cloudprober#299]
We are trying to collect logs from a commands executed as external probe with once mode.
But, current implementation captures stderr only when a probe exits with an error.
It would be helpful when collecting general information from a command.

**Comment by koncha99** [comment]
If this sounds reasonable, we may be able to contribute.

**Comment by zmailloux** [comment]
Worth noting that the probe type EXTERNAL does log info to standard out "Running external command: ...", and will log when it errors. If you do add it, be sure to make sure it works with the `--stderrthreshold=info` flag (IF that's the expected way to control it), which I've tried out and am not sure it's working with any value other than info.

**Comment by manugarg** [comment]
@koncha99 I guess you want stderr only for logging purpose. I guess the right way to do this will be to change the function https://github.com/cloudprober/cloudprober/blob/cd12870f53f9ba3de02610469b3a7c692aea24b3/probes/external/runcmd_linux.go#L33 to return (stdout, stderr, and error), instead of just (stdout and error). We can then either always log command's stderr or provide a probe option to do that. I think an option will be better (log_command_stderr). If my understanding is correct, it sounds good to me. Feel free to send a PR.

@zmailloux  'Running external.. ' is just an info log (docker image is set to send logs to stderr) from cloudprober itself (not from the command being run for the external prober); it should not interfere with logs from the external probe command itself.

**Comment by koncha99** [comment]
Thanks for feedback.
Yes, in my case, I want use stderr of external probe command for logging purpose like external probe with `server mode` does [here](https://github.com/cloudprober/cloudprober/blob/cd12870f53f9ba3de02610469b3a7c692aea24b3/probes/external/external.go#L277).

**Comment by manugarg** [comment]
@koncha99 Thanks for finding the fact that server mode already does that. We don't need another option then. Let's do this by default.

**Comment by manugarg** [comment]
@koncha99 thanks for the PR (#304). I've merged it.

@koncha99 can you share where are you using Cloudprober?

**Comment by koncha99** [comment]
@manugarg Thanks for reviewing. our team manages a Kubernetes platform on our private cloud and provides >1k clusters.
Cloudprober deployed to each cluster is used to measure SLI of platform functionalities. We heavily uses external probe to measure them in E2E user flow.

**Comment by manugarg** [comment]
@koncha99 Pretty, cool. Thanks for sharing that! Sorry for too many questions, but can you share where you work? I am trying to figure out which all companies use Cloudprober :)

**Comment by koncha99** [comment]
Sure, I work for Yahoo! Japan Corporation.

**Comment by manugarg** [comment]
Released v0.12.6. Marking this resolved.
