### ISSUE TITLE
HTTP probes do not recognize change of IP

### ISSUE THREAD

**Issue by ls692** [cloudprober/cloudprober#535]
**Describe the bug**
If a probe target VM is recreated quickly enough and ends up with a new probe IP, HTTP probe still uses the old IP. 

**Cloudprober Version**
All versions of cloudprober are affected.

**Context**
HTTP probes use endpoint.Key() to determine targets that are active and ones need to be recreated
https://github.com/cloudprober/cloudprober/blob/master/probes/http/http.go#L524

endpoint,Key() is defined as Name + labels, excluding IP. https://github.com/cloudprober/cloudprober/blob/master/targets/endpoint/endpoint.go#L41

So if only VM IP changes, we end up reusing the same target but keep probing the old IP.

One simple fix is to modify endpoint.Key() to use the endpoint IP too. I will do some digging to see if that causes other complications. If so, another quickfix is to modify http.go to append IP to endpoint.Key().

**Comment by manugarg** [comment]
Hi Lenin :wave: 😄 ,

Great find. I think this bug must have existed since [Oct, 2022](https://github.com/cloudprober/cloudprober/commit/03cda470703acec464edfa9171b7bc449298fb93), when we started switching to the model of storing IPs in the endpoint struct itself, instead of asking the "targets" to resolve it.

I think modifying endpoint.Key() to include IP should be okay.

**Comment by manugarg** [comment]
Thanks @ls692 for fixing this in #538.
